pipeline {
    /* insert Declarative Pipeline here */
    agent any

    stages {
        stage('Build Jar') {
            steps {
                dir('./09-jenkins-ci-cd/jenkins/volumes/node/workspace/SELENIUM_DOCKER_BUILDER/03-automation-framework/selenium-docker/pom.xml') {
                    bat "mvn clean package -DskipTests"
                }
            }
        }

        stage('Build Image') {
            steps {
                bat "docker build -t=atharvahiwase7/dockerselenium ."
            }
        }

        stage('Push Image') {
            steps {
                bat "docker push atharvahiwase7/dockerselenium"
            }
        }
    }
}