version: "3"
services: 
  hub:
    image: selenium/hub:4.16
    ports: 
    - 4444:4444
  chrome:
    image: selenium/node-chrome:4.17.0-20240123
    shm_size: '2g'
    depends_on:   
    - hub
    environment: 
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  firefox:
    image: selenium/node-firefox:4.16
    shm_size: '2g'
    depends_on:   
    - hub
    environment: 
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
  vendor-portal:
    image: atharvahiwase7/dockerselenium
    depends_on:
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=2
    - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal-output:/home/selenium-docker/test-output
      - ./test-data/mike.json:/home/selenium-docker/test-data/vendor-portal/mike.json
  flight-reservation:
    image: atharvahiwase7/dockerselenium
    depends_on:
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=2
    - TEST_SUITE=flight-reservation.xml
    volumes:
      - ./output/flight-reservation-output:/home/selenium-docker/test-output