pipeline {
    /* insert Declarative Pipeline here */
    agent any

    stages {
        stage('stage-1') {
            steps {
                echo "doing mvn clean"
                echo "doing mvn package"
            }
        }

        stage('stage-2') {
            steps {
                echo "building docker image"
                echo "doing mvn package"
            }
        }
    }

    post {
        always {
            echo "doing clean up"
        }
    }
}